# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [1]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.42953879 0.03462282 0.3680857  ... 0.05545511 0.70404973 0.43696296]
 [0.98537795 0.16508365 0.05356721 ... 0.67959193 0.53846911 0.88335666]
 [0.70852176 0.06742505 0.67897287 ... 0.90734679 0.58437709 0.52841868]
 ...
 [0.51382029 0.17725885 0.37181547 ... 0.81021592 0.5930707  0.97740621]
 [0.84634504 0.88755749 0.5342246  ... 0.06297685 0.78726449 0.37538907]
 [0.07435379 0.02443668 0.90563412 ... 0.08946051 0.06935248 0.21034276]]
[[0.17624751 0.90530555 0.62197926 ... 0.12587233 0.52465166 0.22004492]
 [0.0023953  0.12041477 0.78566706 ... 0.2783746  0.34607612 0.80839784]
 [0.08969246 0.26798703 0.59419979 ... 0.21478899 0.57507363 0.97121345]
 ...
 [0.68050321 0.06364038 0.64071662 ... 0.96600477 0.88623359 0.21566095]
 [0.40143125 0.17084262 0.16596331 ... 0.08960752 0.46928717 0.84736961]
 [0.49351423 0.51075297 0.8945375  ... 0.46672996 0.97295509 0.12547853]]


Без использования numpy

In [3]:
def mult(a, b):
    result = [[0 for _ in range(len(b[0]))] for _ in range(len(a))]
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [4]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [5]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 1.22 s, sys: 1.08 ms, total: 1.22 s
Wall time: 1.25 s


In [6]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.54 ms, sys: 0 ns, total: 1.54 ms
Wall time: 6.29 ms


In [7]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5337064951381763e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.58845822 0.36935804 0.03491262] [0.66598661 0.75131573 0.26298963]


In [8]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [9]:
def np_scalar_product(a,b):
    s = np.dot(a, b)
    return s

In [10]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 423 µs, sys: 0 ns, total: 423 µs
Wall time: 430 µs
CPU times: user 224 µs, sys: 4.14 ms, total: 4.36 ms
Wall time: 4.95 ms


19471.78609264437

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Методы NumPy оказываются эффективнее, потому что они используют векторизованные операции, которые выполняются на уровне нативного кода, что позволяет избежать циклов. Скорость вычислений в NumPy обычно значительно выше, чем в чистом Python, благодаря оптимизированным алгоритмам и использованию библиотеки для работы с массивами данных. Нативные операции NumPy выполняются на уровне C, что делает их гораздо быстрее, чем схожие операции в Python

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [15]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  res = np.sum(np.diag(a)[np.diag(a) % 2 == 0])
  return res

In [17]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[6, 8, 2, 9, 9],
       [2, 7, 9, 2, 9],
       [4, 8, 5, 5, 9],
       [4, 3, 2, 6, 3],
       [7, 9, 8, 8, 8]])

In [18]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 135 µs, sys: 0 ns, total: 135 µs
Wall time: 141 µs


20

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [41]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    A_array = np.array(A)
    result = np.cumsum(A_array, axis=1) / np.arange(1, A_array.shape[1] + 1)
    return result

In [42]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[3.15788603e-02 8.83784493e-01 5.19078102e-02 9.31204013e-01
 6.27873859e-01 1.73832151e-02 6.60444496e-01 5.98488195e-02
 8.02641581e-01 1.26812197e-01 1.37557308e-01 9.22253838e-02
 1.81053017e-01 3.95112403e-01 7.72997793e-01 8.26731131e-03
 2.90590505e-01 8.03022260e-01 4.40035801e-01 8.99454115e-01
 1.24665253e-01 1.34564015e-01 7.77496293e-01 5.41325443e-01
 3.95286237e-01 2.40522333e-01 7.21204367e-01 2.98795865e-01
 6.58095124e-01 4.76735611e-01 7.79149683e-02 9.59329708e-01
 5.48999111e-01 4.95197485e-01 1.34766706e-01 2.18883699e-01
 6.61522289e-01 1.53919094e-01 1.05233415e-01 4.42086817e-01
 5.14633501e-02 3.32323738e-01 5.34306018e-01 2.21138603e-01
 3.46306458e-01 7.92082519e-01 5.48694596e-01 4.07839346e-01
 3.03490054e-01 5.89168484e-01 6.64128106e-01 9.33029339e-01
 4.70471805e-01 2.14217701e-01 6.88285754e-01 3.90829811e-01
 7.73041283e-01 2.73104944e-01 6.86158638e-01 2.83528809e-01
 8.45477538e-01 9.44781583e-01 1.71005018e-01 2.60367417e-01
 8.81566752e-01 2.185223

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [31]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    unique, counts = np.unique(a, return_counts=True)
    result = (unique, counts)
    return result

In [32]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 167 µs, sys: 26 µs, total: 193 µs
Wall time: 200 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [33]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    result = np.copy(X)
    result[1::2] = a
    result[::2] **= 3
    result = result[::-1]
    X = np.concatenate((X, result))
    return X

In [34]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 184 µs, sys: 0 ns, total: 184 µs
Wall time: 265 µs
